# OrderPortal: Settings file.

# This file changes the default values set in the 'settings' dictionary
# defined in the '__init__.py' file.

# You must customize most of these for your own site.

### You should copy this file to 'settings.yaml', which is
### the file that 'app_orderportal.py' looks for by default.

# Official URL to the portal; access from the outside world.
BASE_URL: 'http://my-domain.com/'
# XXX This may be useful for testing on a laptop
# XXX BASE_URL: 'http://localhost:8880/'

# tornado server port; may be different from the above if proxy is used.
PORT: 8880

# CouchDB server
DATABASE_SERVER:   'http://localhost:5984/'
DATABASE_ACCOUNT:  'couchdb_account'
DATABASE_PASSWORD: 'pwd'
DATABASE_NAME:     'orderportal'

# Logging and debug.
TORNADO_DEBUG: true
LOGGING_DEBUG: true
LOGGING_FILEPATH: '/var/log/orderportal/debug.log'

# Login
COOKIE_SECRET: 'Change this to a long string of random characters.'
PASSWORD_SALT: 'Change this to a long string of random characters.'

# Site customization; change for your site
SITE_DIR:           '{ROOT_DIR}/my-site'
SITE_NAME:          'My Order Portal'
SITE_SUPPORT_EMAIL: 'my.email@my-domain.com'

# The icon files must be in the SITE_DIR; absolute file path is not allowed.
SITE_FAVICON:     'orderportal32.png'
SITE_NAVBAR_ICON: 'orderportal32.png'
SITE_HOME_ICON:   'orderportal144.png'

# Account messages definitions
ACCOUNT_MESSAGES_FILEPATH: '{SITE_DIR}/account_messages.yaml'

# Order status, transition, messages definition files
ORDER_STATUSES_FILEPATH:    '{SITE_DIR}/order_statuses.yaml'
ORDER_TRANSITIONS_FILEPATH: '{SITE_DIR}/order_transitions.yaml'
ORDER_MESSAGES_FILEPATH:    '{SITE_DIR}/order_messages.yaml'

# Use sequentially numbered order identifiers
ORDER_IDENTIFIER_FORMAT: 'MY{0:=05d}'
ORDER_IDENTIFIER_REGEXP: 'MY\d+'

# The statuses to show in the orders list.
# The statuses must be defined in the ORDER_STATUSES_FILEPATH file.
ORDERS_LIST_STATUSES:
  - submitted
  - accepted
  - processing
  - closed

# University symbols (abbreviations), names and rank in list.
# Optional, may be set to null.
UNIVERSITIES_FILEPATH: '{SITE_DIR}/swedish_universities.yaml'

# Country names and codes. Optional, may be set to null.
COUNTRY_CODES_FILEPATH: '{SITE_DIR}/country_codes.yaml'

# Subject codes, terms in a hierarchy. Optional, may be set to null.
SUBJECT_TERMS_FILEPATH: '{SITE_DIR}/subject_terms.yaml'

# Messages; email server info.
MESSAGE_SENDER_EMAIL: '"OrderPortal Support" <support@my-domain.com>'
EMAIL:
  HOST: 'localhost'
